using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Globalization;
using System.Linq;
using Microsoft.Win32;
using System.Net.Http;
using System.Net.WebSockets;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using BepInEx;
using BepInEx.Configuration;
using BepInEx.Logging;
using BepInEx.Unity.IL2CPP;
using HarmonyLib;
using Il2CppInterop.Runtime;
using Il2CppInterop.Runtime.InteropTypes.Arrays;
using NAudio.CoreAudioApi;
using NAudio.Wave;
using TMPro;
using UnityEngine;
using UnityEngine.Localization.Settings;
using UnityEngine.UI;
using UI.Common;
using UI.TraySetting;

namespace LilithTextInjector;

[HarmonyPatch(typeof(DialogueManager), "Update")]
internal static partial class DialogueManagerUpdatePatch
{
    private static GameObject? _inputBubble;
    private static TMP_InputField? _inputField;
    private static TextMeshProUGUI? _inputPlaceholder;
    private static bool _focusNextFrame;
    private static readonly ConcurrentQueue<string> PendingReplies = new();
    private static readonly ConcurrentQueue<string> PendingAiEmotions = new();
    private static readonly ConcurrentQueue<string> PendingTranscripts = new();
    private static readonly ConcurrentQueue<string> PendingTranscriptionErrors = new();
    private static readonly ConcurrentQueue<VoiceSequence> PendingVoiceAudio = new();
    private static readonly ConcurrentQueue<GeneratedAiNote> PendingAiNotes = new();
    private static readonly ConcurrentQueue<GeminiToolBatch> PendingGeminiToolBatches = new();
    private static readonly ConcurrentQueue<GeminiAgentSession> PendingGeminiCompatibilityFallbacks = new();
    private static readonly ConcurrentQueue<QwenToolBatch> PendingQwenToolBatches = new();
    private static readonly object AiNoteLock = new();
    private static AiNoteState _aiNoteState = new();
    private static bool _aiNoteGenerationInFlight;
    private static float _nextAiNoteCheckAt;
    private static byte[]? _delayedSpeechAudio;
    private static float _delayedSpeechPlayAt = -1f;
    private static float _voicePitchResetAt = -1f;
    private static readonly HttpClient Http = new() { Timeout = TimeSpan.FromSeconds(90) };
    private static bool _requestInFlight;
    private static bool _transcriptionInFlight;
    private static bool _aiPagesAwaitingAdvance;
    private static string _currentAiPageText = string.Empty;
    private static float _aiTypingFinishedAt = -1f;
    private static int _repliesSincePlayerNameWasOffered = 3;
    private static readonly object MemoryLock = new();
    private static readonly List<ChatTurn> RecentConversation = new();
    private static readonly string MemoryDirectory = Path.Combine(Paths.BepInExRootPath, "data", "LilithTextInjector");
    private static readonly string MemoryPath = Path.Combine(MemoryDirectory, "memory.json");
    private static readonly string AiNoteStatePath = Path.Combine(MemoryDirectory, "ai-note-state.json");
    private static readonly string ApplicationLauncherPath = Path.Combine(MemoryDirectory, "applications.json");
    private static readonly object WindowsStartAppsLock = new();
    private static readonly List<WindowsStartApplication> CachedWindowsStartApps = new();
    private static DateTimeOffset _windowsStartAppsLoadedAt = DateTimeOffset.MinValue;
    private static readonly string UnvoicedManifestPath = Path.Combine(MemoryDirectory, "unvoiced-native-lines.tsv");
    private static readonly object UnvoicedManifestLock = new();
    private static readonly HashSet<int> RecordedUnvoicedNodeIds = new();
    private static readonly Dictionary<int, string> NativeVoiceFilesByLineId = new();
    private static readonly Dictionary<int, float> NativeVoiceDurationByNodeId = new();
    private static string _loadedNativeVoicePackDirectory = string.Empty;
    private static int _lastInjectedNativeNodeId = -1;
    private static float _lastInjectedNativeVoiceAt = -10f;
    private static int _lastObservedNativeNodeId = -1;
    private static bool _nativeDatabaseDumpCompleted;
    private static bool _localizedLineDatabasesDumped;
    private const int MaxRememberedTurns = 32;
    private static DateTimeOffset _weatherFetchedAt = DateTimeOffset.MinValue;
    private static string _cachedWeatherContext = string.Empty;
    private static bool _ipWeatherLocationResolved;

    private static float _nextJapaneseVoiceUiScanAt;
    private static string _lastObservedVoiceLanguage = string.Empty;
    private static readonly HashSet<string> LoggedVoiceUiObjects = new();
    private static bool? _japaneseVoiceOverride;
    private static bool _voicePreferenceInitialized;
    private static bool _voicePreferenceAppliedToNativeUi;
    private static float _nextJapaneseVoiceToggleRestoreAt;
    private static bool _voiceHostLaunchAttempted;
    private static Process? _voiceHostProcess;
    private static bool? _voiceHostJapaneseMode;
    private static float _voiceHostRestartAt;
    private static IntPtr _apiKeyTrayPointer;
    private static bool _apiKeyDialogMode;
    private static volatile bool _apiKeyOpenRequested;
    private static float _apiKeyOpenRequestedAt = -1f;
    private static bool _apiKeyMissingViewLogged;
    private static GiftExchangeView? _apiKeyView;
    private static string _pendingApiKeyProvider = "Gemini";
    private static readonly List<ApiKeyDialogLabelSnapshot> ApiKeyDialogLabels = new();
    private static bool _apiKeyDialogStateCaptured;
    private static TMP_InputField.ContentType _apiKeyOriginalContentType;
    private static TMP_InputField.LineType _apiKeyOriginalLineType;
    private static int _apiKeyOriginalCharacterLimit;
    private static bool _microphoneRecording;
    private static float _microphoneStartedAt;
    private static WasapiCapture? _wasapiCapture;
    private static MemoryStream? _wasapiStream;
    private static WaveFileWriter? _wasapiWriter;
    private static readonly object WasapiLock = new();
    private static readonly ConcurrentQueue<byte[]> ParaformerAudioChunks = new();
    private static Task<string>? _paraformerSessionTask;
    private static CancellationTokenSource? _paraformerCancellation;
    private static volatile bool _paraformerFinishRequested;
    private static WaveFormat? _voiceCaptureFormat;
    private static double _paraformerResampleAccumulator;
    private static string? _pendingVoiceSubmitText;
    private static float _pendingVoiceSubmitAt = -1f;
    private static bool _testNoteAttempted;
    private static float _nextAdvancedActionsUiScanAt;
    private static GameObject? _advancedActionsRow;
    private static ButtonToggle? _advancedActionsToggle;
    private static Il2CppSystem.Action<bool>? _advancedActionsChanged;
    private static float _nextKeyBindingsUiScanAt;
    private static GameObject? _textInputKeyRow;
    private static GameObject? _voiceInputKeyRow;
    private static RectTransform? _textInputKeyButtonRect;
    private static RectTransform? _voiceInputKeyButtonRect;
    private static ButtonToggle? _textInputKeyButton;
    private static ButtonToggle? _voiceInputKeyButton;
    private static TMP_Text? _textInputKeyValue;
    private static TMP_Text? _voiceInputKeyValue;
    private static int _keyBindingTarget;
    private static float _keyBindingStartedAt = -1f;
    private static bool _textInputKeyWasDown;
    private static bool _voiceInputKeyWasDown;
    private static readonly HashSet<int> RebindingHeldVirtualKeys = new();
    private static TraySettingView? _settingsView;
    private static GameObject? _settingsVisibilityTemplateRow;
    private static float _nextForegroundWindowScanAt;
    private static IntPtr _lastExternalForegroundWindow;
    private static readonly List<LocalTimer> LocalTimers = new();
    private static PendingSystemAction? _pendingSystemAction;
    private static readonly ConcurrentQueue<CodexBridgeSignal> PendingCodexSignals = new();
    private static readonly string CodexBridgeEventsDirectory = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "LilithAiMod", "CodexBridge", "events");
    private static float _nextCodexBridgePollAt;
    private static float _nextCodexSignalAt;

}
